name: "Daily Commit by 22f3002867@ds.study.iitm.ac.in"

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp
        run: echo 'Last run: '"$(date -u)" > daily_commit.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add daily_commit.txt
          git commit -m "Automated commit [skip ci]" || exit 0
          git push
